name: my workflow

on: 
    push:
        branches: 
           - dev

jobs:
    myjob:
        runs-on: ubuntu-latest

        steps:
            - name: hello bunny
              run: echo " hello dude"




